repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      sha: fa7a3b5466bfb37fb6c76a20701d58a6b9caa3c5
      hooks:
        - id: trailing-whitespace
          types: [file, python]
        - id: autopep8-wrapper
          types: [python]
          args: ['-i']
        - id: fix-encoding-pragma
          types: [python]
        - id: double-quote-string-fixer 
          types: [python]
        - id: end-of-file-fixer
          types: [file, python]
        - id: mixed-line-ending
          types: [file, python]
        - id: check-merge-conflict
          types: [file]
        - id: flake8
          types: [python]
          args: ["--ignore=E741"]
    - repo: git://github.com/pre-commit/mirrors-yapf
      sha: v0.22.0
      hooks:
          - id: yapf
            types: [python]
            args: ['-i']

