repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      sha: v1.1.1
      hooks:
        - id: trailing-whitespace
          types: [file, python]
        - id: flake8
          types: [python]
          args: ["--ignore=E702"]
        - id: autopep8-wrapper
          types: [python]
          args: ['-i', '--ignore=E702']
        - id: double-quote-string-fixer
          types: [python]
        - id: fix-encoding-pragma
          types: [python]
