repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
        - id: trailing-whitespace
          types: [file, python]
        - id: flake8
          types: [python]
          args: ["--ignore=E702 F401"]
        - id: autopep8-wrapper
          types: [python]
          args: ['-i', '--ignore=E702']
        - id: fix-encoding-pragma
          types: [python]
        - id: double-quote-string-fixer 
          types: [python]
        - id: end-of-file-fixer
          types: [file, python]
        - id: mixed-line-ending
          types: [file, python]
