repos:
    - repo: git://github.com/pre-commit/pre-commit-hooks
      sha: origin
      hooks:
        - id: trailing-whitespace
          types: [file, python]
        - id: flake8
          types: [python]
          args: ["--ignore=E712 E702 F401 E999 E402"]
        - id: autopep8-wrapper
          types: [python]
          args: ['-i', '--ignore=E712 E702 E999 E402']
        - id: fix-encoding-pragma
          types: [python]
        - id: double-quote-string-fixer 
          types: [python]
        - id: end-of-file-fixer
          types: [file, python]
        - id: mixed-line-ending
          types: [file, python]
        - id: check-merge-conflict
          types: [file]
    - repo: git://github.com/pre-commit/mirrors-yapf
      sha: origin
      hooks:
          - id: yapf
            types: [python]
            args: ['-i']

